module.exports = {
    GET_DASHBOARDS: 'GET_DASHBOARDS',
    GET_DASHBOARD: 'GET_DASHBOARD',
    RECEIVE_DATA: 'RECEIVE_DATA',
    REQUEST_DATA: 'REQUEST_DATA',
    DELETE_DASHBOARD: 'DELETE_DASHBOARD',
    UPDATE_DASHBOARD: 'UPDATE_DASHBOARD',
    ADD_DASHBOARD: 'ADD_DASHBOARD'
}